#!/usr/bin/env bash

# Add Logged user to groups
sudo usermod -aG storage,network $USER


# Secure MariaDB & create DB/user
mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql

# Setup services
systemctl enable --now nginx php-fpm mariadb


read -p "Do you want to set up WordPress? (y/n): " answer

if [[ "$answer" == "y" ]]; then
    echo "Setting up WordPress..."
    sh <(curl -Lks raw.githubusercontent.com/DerJimno/wp-setup/main/setup)
fi
