#!/usr/bin/env bash

# Configure brightness
echo "ACTION==\"add\", SUBSYSTEM==\"backlight\", \
RUN+=\"/bin/chgrp video \$sys\$devpath/brightness\", \
RUN+=\"/bin/chmod g+w \$sys\$devpath/brightness\"" | \
sudo tee /etc/udev/rules.d/backlight.rules


# Configure uinput
echo "KERNEL==\"uinput\", MODE=\"0660\", GROUP=\"uinput\", \
OPTIONS+=\"static_node=uinput\"" | \
sudo tee /etc/udev/rules.d/99-input.rules
sudo modprobe uinput


# Configure default sound card
echo "defaults.pcm.card 1
defaults.ctl.card 1" | \
sudo tee /etc/asound.conf


# Configure notifications 
echo "[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/lib/notification-daemon-1.0/notification-daemon" | \
sudo tee /usr/share/dbus-1/services/org.freedesktop.Notifications.service


# Login-manager (ly)
systemctl enable ly.service


